In [1]:
import pandas as pd
import numpy as np

In [2]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("BrotherTony/employee-burnout-turnover-prediction-800k")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
print(ds)

DatasetDict({
    train: Dataset({
        features: ['employee_id', 'role', 'job_level', 'department', 'tenure_months', 'salary', 'performance_score', 'satisfaction_score', 'workload_score', 'team_sentiment', 'recent_feedback', 'communication_patterns', 'project_completion_rate', 'overtime_hours', 'training_participation', 'collaboration_score', 'technical_skills', 'soft_skills', 'email_sentiment', 'slack_activity', 'meeting_participation', 'goal_achievement_rate', 'stress_level', 'burnout_risk', 'left_company', 'turnover_reason', 'risk_factors_summary', 'turnover_probability_generated', 'persona_name', 'role_complexity_score', 'career_progression_score'],
        num_rows: 849999
    })
})

In [5]:
#Converting it into dataframe
df = ds['train'].to_pandas()

In [6]:
print('Rows:',df.shape[0])
print('Columns:',df.shape[1])

Rows: 849999
Columns: 31

In [7]:
df.head()

,employee_id,role,job_level,department,tenure_months,salary,performance_score,satisfaction_score,workload_score,team_sentiment,...,goal_achievement_rate,stress_level,burnout_risk,left_company,turnover_reason,risk_factors_summary,turnover_probability_generated,persona_name,role_complexity_score,career_progression_score
0,SYN_00000000,,Mid,Research & Development,169,79704.579059,0.632482,0.623746,0.758117,0.662335,...,0.632482,0.908992,0.866643,False,Not Applicable,Severe Burnout Risk,0.290979,ChangeResistor,0.2,1.000000
1,SYN_00000001,Customer Success Manager,Manager,Research & Development,54,29694.288831,0.538587,0.982556,0.788416,0.934661,...,0.538587,0.363321,0.218996,False,Not Applicable,Low Risk,0.156002,NewEnthusiast,0.2,1.000000
2,SYN_00000002,Administrative Assistant,Entry,HR,1,62208.470185,0.624656,0.767200,0.697617,0.888559,...,0.624656,0.664378,0.541531,True,Personal / Relocation,Low Risk,0.233897,NewEnthusiast,0.2,0.836495
3,SYN_00000003,Senior Manager,Manager,Research & Development,31,236066.567114,0.959320,0.185888,0.493143,0.732189,...,0.959320,1.000000,1.000000,False,Not Applicable,Severe Burnout Risk,0.351682,OverachievingSprinter,0.2,1.000000
4,SYN_00000004,Anonymous Employee,Mid,Research & Development,131,37306.328156,0.677305,0.566706,0.567230,0.817545,...,0.677305,0.723049,0.614825,False,Not Applicable,Low Risk,0.272910,SeasonedExpert,0.2,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 849999 entries, 0 to 849998
Data columns (total 31 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   employee_id                     849999 non-null  object
 1   role                            849999 non-null  object
 2   job_level                       849999 non-null  object
 3   department                      849999 non-null  object
 4   tenure_months                   849999 non-null  int64
 5   salary                          849999 non-null  float64
 6   performance_score               849999 non-null  float64
 7   satisfaction_score              849999 non-null  float64
 8   workload_score                  849999 non-null  float64
 9   team_sentiment                  849999 non-null  float64
 10  recent_feedback                 849999 non-null  object
 11  communication_patterns          849999 non-null  object
 12  project_completion_rate         849999 non-null  float64
 13  overtime_hours                  849999 non-null  float64
 14  training_participation          849999 non-null  float64
 15  collaboration_score             849999 non-null  float64
 16  technical_skills                849999 non-null  object
 17  soft_skills                     849999 non-null  object
 18  email_sentiment                 849999 non-null  float64
 19  slack_activity                  849999 non-null  float64
 20  meeting_participation           849999 non-null  float64
 21  goal_achievement_rate           849999 non-null  float64
 22  stress_level                    849999 non-null  float64
 23  burnout_risk                    849999 non-null  float64
 24  left_company                    849999 non-null  bool
 25  turnover_reason                 849999 non-null  object
 26  risk_factors_summary            849999 non-null  object
 27  turnover_probability_generated  849999 non-null  float64
 28  persona_name                    849999 non-null  object
 29  role_complexity_score           849999 non-null  float64
 30  career_progression_score        849999 non-null  float64
dtypes: bool(1), float64(18), int64(1), object(11)
memory usage: 195.4+ MB

In [9]:
#Checking Null values
df.isnull().sum()

employee_id                       0
role                              0
job_level                         0
department                        0
tenure_months                     0
salary                            0
performance_score                 0
satisfaction_score                0
workload_score                    0
team_sentiment                    0
recent_feedback                   0
communication_patterns            0
project_completion_rate           0
overtime_hours                    0
training_participation            0
collaboration_score               0
technical_skills                  0
soft_skills                       0
email_sentiment                   0
slack_activity                    0
meeting_participation             0
goal_achievement_rate             0
stress_level                      0
burnout_risk                      0
left_company                      0
turnover_reason                   0
risk_factors_summary              0
turnover_probability_generated    0
persona_name                      0
role_complexity_score             0
career_progression_score          0
dtype: int64

In [10]:
#Describing data
df.describe()

,tenure_months,salary,performance_score,satisfaction_score,workload_score,team_sentiment,project_completion_rate,overtime_hours,training_participation,collaboration_score,email_sentiment,slack_activity,meeting_participation,goal_achievement_rate,stress_level,burnout_risk,turnover_probability_generated,role_complexity_score,career_progression_score
count,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000,849999.000000
mean,70.380999,84563.069751,0.692027,0.581941,0.599490,0.666848,0.595412,3.132903,0.279344,0.473380,0.582392,0.473380,0.473380,0.692027,0.791048,0.735941,0.285327,0.210859,0.841147
std,50.177033,47444.308564,0.183911,0.276268,0.200038,0.178232,0.161173,6.094207,0.221602,0.184961,0.277255,0.184961,0.184961,0.183911,0.264536,0.315756,0.087902,0.085018,0.182216
min,1.000000,27190.569289,0.074113,0.050000,0.006741,0.019774,0.059290,0.000000,0.000079,0.008674,0.042500,0.008674,0.008674,0.074113,0.000000,0.000000,0.131127,0.200000,0.182198
25%,30.000000,41006.776951,0.571340,0.367016,0.455657,0.545729,0.490179,0.000000,0.103691,0.332366,0.367212,0.332366,0.332366,0.571340,0.613005,0.479950,0.227733,0.200000,0.713997
50%,67.000000,78178.525918,0.699235,0.583188,0.613744,0.686320,0.609499,0.000000,0.223123,0.457102,0.583141,0.457102,0.457102,0.699235,0.942151,0.914494,0.299657,0.200000,0.911793
75%,105.000000,116146.639606,0.825585,0.813912,0.756693,0.806540,0.716149,4.161240,0.400716,0.600885,0.811581,0.600885,0.600885,0.825585,1.000000,1.000000,0.335272,0.200000,1.000000
max,357.000000,384330.428656,1.000000,1.000000,0.999615,0.999956,1.000000,73.953574,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.899983,1.000000,1.000000

In [11]:
#df = df.applymap(lambda x: tuple(x) if isinstance(x, np.ndarray) else x)
#df.duplicated().sum()

In [12]:
#total duplicate values for str type
df.astype(str).duplicated().sum()

np.int64(0)

In [13]:
#num_col=list(df.select_dtypes(include=[int,float]))
num_col=df.select_dtypes(include=['int','float'])
num_col

,tenure_months,salary,performance_score,satisfaction_score,workload_score,team_sentiment,project_completion_rate,overtime_hours,training_participation,collaboration_score,email_sentiment,slack_activity,meeting_participation,goal_achievement_rate,stress_level,burnout_risk,turnover_probability_generated,role_complexity_score,career_progression_score
0,169,79704.579059,0.632482,0.623746,0.758117,0.662335,0.524187,0.000000,0.044373,0.492131,0.632891,0.492131,0.492131,0.632482,0.908992,0.866643,0.290979,0.2,1.000000
1,54,29694.288831,0.538587,0.982556,0.788416,0.934661,0.558206,0.000000,0.314858,0.981394,1.000000,0.981394,0.981394,0.538587,0.363321,0.218996,0.156002,0.2,1.000000
2,1,62208.470185,0.624656,0.767200,0.697617,0.888559,0.566849,0.000000,0.744900,0.701138,0.758005,0.701138,0.701138,0.624656,0.664378,0.541531,0.233897,0.2,0.836495
3,31,236066.567114,0.959320,0.185888,0.493143,0.732189,0.767456,9.591680,0.298170,0.339626,0.202517,0.339626,0.339626,0.959320,1.000000,1.000000,0.351682,0.2,1.000000
4,131,37306.328156,0.677305,0.566706,0.567230,0.817545,0.597235,0.000000,0.134719,0.565582,0.559722,0.565582,0.565582,0.677305,0.723049,0.614825,0.272910,0.2,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849994,23,86074.280652,0.459260,0.344079,0.260582,0.605880,0.367408,6.581391,0.134792,0.322420,0.331645,0.322420,0.322420,0.459260,1.000000,1.000000,0.339457,0.2,0.465464
849995,12,120962.927457,0.615596,0.299675,0.255428,0.679089,0.492477,8.941025,0.028266,0.326591,0.294625,0.326591,0.326591,0.615596,1.000000,1.000000,0.343116,0.2,0.397798
849996,119,101252.086922,0.712229,0.976399,0.496662,0.905338,0.689116,23.610166,0.085303,0.950605,1.000000,0.950605,0.950605,0.712229,0.403338,0.256156,0.160417,0.2,1.000000
849997,132,93101.157471,0.529667,0.567002,0.652544,0.724445,0.505384,0.000000,0.050257,0.499141,0.555711,0.499141,0.499141,0.529667,0.591745,0.455200,0.254504,0.2,0.854833
849998,17,157391.495493,0.832715,0.427700,0.825428,0.705534,0.666172,0.000000,0.181219,0.431732,0.445603,0.431732,0.431732,0.832715,1.000000,1.000000,0.327408,0.2,0.927191

In [14]:
#cat_col=list(df.select_dtypes(include=object))
cat_col=df.select_dtypes(include=['object','category'])
cat_col

,employee_id,role,job_level,department,recent_feedback,communication_patterns,technical_skills,soft_skills,turnover_reason,risk_factors_summary,persona_name
0,SYN_00000000,,Mid,Research & Development,Close to home and good shift time given Slow i...,Exhibits communication style typical of a Chan...,"[REST APIs, Python (Pandas, NumPy, SciPy), Lin...","[Communication, Creativity, Teamwork, Conflict...",Not Applicable,Severe Burnout Risk,ChangeResistor
1,SYN_00000001,Customer Success Manager,Manager,Research & Development,HSBC Software Development Pune India Review Gr...,Exhibits communication style typical of a NewE...,"[Network Security, GCP, dbt, Express.js, Docke...","[Conflict Resolution, Problem Solving, Creativ...",Not Applicable,Low Risk,NewEnthusiast
2,SYN_00000002,Administrative Assistant,Entry,HR,Great opportunity for growth if you drink the ...,Exhibits communication style typical of a NewE...,"[Node.js, dbt, CI/CD Pipelines, Angular, Ruby ...","[Problem Solving, Critical Thinking, Teamwork,...",Personal / Relocation,Low Risk,NewEnthusiast
3,SYN_00000003,Senior Manager,Manager,Research & Development,Fabulous people and broad opportunities The ch...,Exhibits communication style typical of a Over...,"[Ruby on Rails, GraphQL, Python (Django, Flask...","[Emotional Intelligence, Leadership, Conflict ...",Not Applicable,Severe Burnout Risk,OverachievingSprinter
4,SYN_00000004,Anonymous Employee,Mid,Research & Development,"The harder you work, the faster you climb. I w...",Exhibits communication style typical of a Seas...,"[Vue.js, XGBoost, ETL/ELT Pipelines, Linux/Uni...","[Critical Thinking, Communication, Creativity,...",Not Applicable,Low Risk,SeasonedExpert
...,...,...,...,...,...,...,...,...,...,...,...
849994,SYN_00849994,Consultant,Mid,R&D,Kein Schatten ohne Sonne We do not review who ...,Exhibits communication style typical of a Burn...,"[AWS, Data Warehousing (Snowflake, BigQuery, R...","[Teamwork, Critical Thinking, Leadership, Ment...",Not Applicable,Severe Burnout Risk,BurntOutStar
849995,SYN_00849995,Associate,Entry,Sales,Overall quite positive experience with a few a...,Exhibits communication style typical of a 9-to...,"[Site Reliability Engineering (SRE), AWS, Apac...","[Adaptability, Mentorship, Critical Thinking, ...",Compensation / Role Dissatisfaction,Severe Burnout Risk,9-to-5Clockwatcher
849996,SYN_00849996,Senior Consultant,Senior,Operations,Nice environment and friendly colleagues Fast-...,Exhibits communication style typical of a Stea...,"[Go, Statistics, Webpack, Data Modeling]","[Teamwork, Conflict Resolution, Mentorship, Le...",Not Applicable,Low Risk,SteadyEddy
849997,SYN_00849997,Analyst,Mid,Sales & Marketing,"structured, many events to participate in, can...",Exhibits communication style typical of a 9-to...,"[Rust, Webpack, Express.js, SQL]","[Creativity, Time Management, Leadership, Comm...",Personal / Relocation,Low Risk,9-to-5Clockwatcher
849998,SYN_00849998,Current Employee - Anonymous Employee,Mid,Operations,The main challenge is to maintain the atmosphe...,Exhibits communication style typical of a Over...,"[XGBoost, REST APIs, Svelte, ETL/ELT Pipelines]","[Adaptability, Teamwork, Problem Solving, Crea...",Not Applicable,Severe Burnout Risk,OverachievingSprinter

In [15]:
bool_col=df.select_dtypes(include='bool').columns
df[bool_col]= df[bool_col].astype(int)

In [16]:
print('Categorical columns count:',len(list(cat_col)))
print('Numerical columns count:',len(list(num_col)))
print('Boolean columns count:',len(bool_col))

Categorical columns count: 11
Numerical columns count: 19
Boolean columns count: 1

In [17]:
list(cat_col)

['employee_id',
 'role',
 'job_level',
 'department',
 'recent_feedback',
 'communication_patterns',
 'technical_skills',
 'soft_skills',
 'turnover_reason',
 'risk_factors_summary',
 'persona_name']

In [18]:
#for cat in list(cat_col):
#    print(df[cat].unique())
for cat in cat_col:
    try:
        print(cat, ":", df[cat].unique())
    except Exception as e:
        print(cat, "❌ ERROR →", e)

employee_id : ['SYN_00000000' 'SYN_00000001' 'SYN_00000002' ... 'SYN_00849996'
 'SYN_00849997' 'SYN_00849998']
role : [' ' ' Customer Success Manager' ' Administrative Assistant'
 ' Senior Manager' ' Anonymous Employee' ' Senior Business Analyst'
 ' Sales' ' Support Worker' ' Customer Advisor' ' Senior Consultant'
 ' Manager' ' Sales Assistant' ' Consultant' ' Team Member'
 ' Project Manager' 'Production Technician I'
 ' Software Development Engineer II' ' Accountant' ' Audit Associate'
 'Former Employee - Anonymous Employee' ' Crew Member/Grill Cook'
 ' Customer Service Representative' ' Crew Member'
 ' Customer Service Assistant' ' IT Consultant' ' Retail Sales Assistant'
 ' Business Manager' ' Research Associate' ' Analyst' ' Tax Associate'
 ' Lecturer' ' Audit Senior Associate' ' Audit Manager'
 'Software Engineer' ' Operations Analyst' ' Director'
 ' Assistant Manager' ' Housekeeper' ' Software Engineer' ' Specialist'
 'Sales Executive' ' Senior Associate' ' Retail Assistant' ' Associate'
 ' Programmer Analyst' 'Current Employee - Anonymous Employee'
 ' Assistant Vice President' ' Principal' ' Senior Account Executive'
 ' PhD Student' ' Administrative' ' Advisory Manager' ' Store Manager'
 ' Line Cook' ' Branch Manager' ' Financial Analyst' ' IT Analyst'
 ' Mac Specialist (Apple Store)' ' Family Room Specialist'
 ' Sales Associate' ' Recruitment Consultant' ' Software Developer'
 ' Senior Software Engineer' ' Account Manager' ' Crew'
 ' Senior Vice President' ' Human Resources' ' Business Analyst'
 ' Engagement Manager' ' Principal Software Engineer' ' Student'
 ' Marketing Manager' ' Customer Service Associate' ' Vice President'
 ' Senior Analyst' ' Program Manager' ' Marketing' ' Optical Assistant'
 'Manager' 'Laboratory Technician' ' Cashier' ' Associate Consultant'
 ' Applications Engineer' ' Systems Analyst' ' Shop Assistant'
 ' Tax Senior' ' Student Ambassador' ' Research Analyst' ' Server'
 ' Finance Manager' ' Senior Systems Engineer' ' Intern'
 ' Customer Assistant' ' Warehouse Operative' ' Audit Senior'
 ' General Manager' ' Sales Associate/Cashier' ' Staff Software Engineer'
 'Current Employee - Software Engineer' ' Auditor' ' Deputy Manager'
 ' Customer Service Advisor' ' Apple Genius'
 ' Business Technology Analyst' ' User Experience Designer'
 ' Senior Director' ' Technical Support Engineer' 'nan' ' Technical Lead'
 'Sales Representative' ' Staff Consultant' ' Team Lead'
 ' Retail Sales Associate' ' Recruiter' ' Mcdonalds Crew Member'
 ' Sales Manager' ' Engineer' 'Senior Software Engineer' ' Shift Manager'
 ' Assistant' ' Principal Consultant' ' Product Manager' ' Team Manager'
 ' Sales Consultant' ' Software Engineer II' ' Supervisor' ' Crew Trainer'
 ' Executive' ' Customer Service' ' Operations Manager' ' Part'
 ' Product Specialist' 'Current Employee - Specialist'
 ' Senior Software Development Engineer' ' Investment Banking Analyst'
 ' Waitress' ' Audit Assistant' ' Intern ' ' Senior Developer'
 ' Managing Director' ' Business Development' ' Account Executive'
 ' McDonalds Crew Trainer' ' Senior Member of Technical Staff'
 'Former Employee - Software Engineer' ' Personal Assistant'
 ' Receptionist' ' IT Specialist' 'Manufacturing Director'
 ' Actuarial Analyst' ' Advisor' ' Researcher' ' Sales Executive'
 ' Human Resources Manager' ' Front Desk Receptionist'
 ' Executive Assistant' ' Vice President '
 'Current Employee - Senior Software Engineer' ' Teller'
 ' Relationship Manager' ' Administrator' ' Sales Advisor' ' Cook'
 ' Checkout Operator' ' Bank Teller' ' Sales Representative'
 ' Senior Auditor' ' Bartender'
 'Current Employee - Senior Program Manager' ' Applications Developer'
 ' Senior Associate ' ' Anonymous' ' Associate Director'
 ' Research Assistant' ' Team Leader' ' Supermarket Assistant'
 ' Network Engineer' ' Senior Engineer' ' Financial Advisor'
 ' Support Engineer' 'Former Employee - Specialist'
 'Former Employee - Software Development Engineer' ' Data Scientist'
 ' Tax Manager' ' Department Manager' ' Senior' ' Chef'
 ' Front Desk Agent' ' Customer Service Specialist' 'Research Scientist'
 ' Devops Engineer' 'Current Employee - Program Manager'
 ' Senior Project Manager' ' Finance' ' Managing Consultant'
 ' Apple At Home Advisor' ' Systems Administrator' ' Tax Consultant'
 ' Internship' ' Finance Analyst' ' Associate Systems Engineer'
 ' Executive Director' ' Senior Software Developer' ' Sales Director'
 ' Delivery Driver' ' Sales Specialist' ' Management'
 ' Business Development Manager' ' Business Development Representative'
 ' Product Marketing Manager' ' Senior Product Manager'
 ' Advisory Software Engineer' ' Software Development Engineer'
 ' Senior Financial Analyst' ' Developer' ' Systems Engineer'
 ' Registered Nurse' ' Operations' ' Customer Service Agent'
 ' Night Auditor' ' Associate Software Engineer'
 ' Senior Associate Consultant' ' Assurance Associate'
 ' Operations Specialist' ' IT Manager' ' Technical Specialist'
 ' Customer Assistant Tesco' 'Research Director' ' Trading Assistant'
 ' Staff' ' Data Analyst' ' Technology Analyst'
 ' Human Resources Business Partner' ' Senior Marketing Manager'
 ' Shift Leader' ' Store Assistant' ' Waitrose Supermarket Assistant'
 ' Graduate Student' ' Service Delivery Manager' ' Senior Accountant'
 ' Member Of Technical Staff' ' Associate Partner' ' Designer'
 ' General Assistant' ' Personal Banker' ' Relationship Banker'
 ' Project Leader' 'Current Employee - Software Development Engineer'
 ' Operations Supervisor' ' Software Development Engineer In Test (SDET)'
 ' Cabin Crew' ' Advisory Associate' ' Cleaner' ' Mac Genius'
 'Data Scientist' ' Partner' 'Current Employee - Warehouse Associate'
 ' Experienced Audit Associate' ' Business Development Consultant'
 ' Postdoctoral Research Associate' ' Assistant Store Manager'
 'Former Employee - Warehouse Associate' ' Audit Staff'
 'Healthcare Representative' ' Tax Senior Associate'
 ' Senior Managing Consultant' ' Staff Accountant' ' Security Officer'
 'Current Employee - Software Development Engineer II'
 ' Senior Program Manager' ' Solutions Architect' ' Manager '
 ' Management Consultant' ' AVP' ' McDonalds Cashier'
 ' Senior Applications Developer' ' Technology Consultant'
 'Human Resources' ' Associate Analyst' ' Project Coordinator'
 ' Warehouse Worker' ' Shop Floor Assistant'
 'Current Employee - Fulfillment Associate' ' SAP Consultant'
 ' Customer Service Executive' ' Senior Audit Associate' ' Server/Waiter'
 ' Senior Executive' ' Inside Sales Representative' ' Graduate'
 ' Technical Consultant' ' Fry Cook' ' Architect' ' Technician'
 ' IT Project Manager' ' Genius' ' Risk Analyst' ' Driver' ' Tax Analyst'
 ' Senior Account Manager']
job_level : ['Mid' 'Manager' 'Entry' 'Senior' 'Lead']
department : ['Research & Development' 'HR' 'Dairy' 'Procurement' 'Meats'
 'Sales & Marketing' 'Technology' 'Operations' 'Sales' 'Legal'
 'Processed Foods' 'R&D' 'Analytics' 'Produce' 'Customer Service'
 'Production       ' 'Bakery' 'Finance' 'Human Resources' 'Admin Offices'
 'nan' 'Store Management' 'HR Technology' 'IT/IS' 'Software Engineering'
 'Audit' 'Accounts Receiveable' 'Labor Relations' 'Training' 'Investment'
 'Accounting' 'Accounts Payable' 'Compensation' 'Information Technology'
 'Recruitment' 'Executive' 'Executive Office' 'Employee Records']
recent_feedback : ['Close to home and good shift time given Slow in agility\r\nHierarchical structure\r\nStrong Bureaucracy Needs a bigger focus on inclusion (as does 99.9% of every corporation).'
 'HSBC Software Development Pune India Review Great perks and benefits\r\n4. Good benefits, decent starting pay, work form home oppurtunities Pretty good place to work'
 'Great opportunity for growth if you drink the kool-aid. The recruiting process is tough! Smart people, beginnings of a culture.'
 'Fabulous people and broad opportunities The chains metamorphosed into bills and the whip into peer judgment. Can have work weeks that are in excess of 80 hours during the height of busy season.'
 "The harder you work, the faster you climb. I would never recommend working here if you didn't have too!"
 'There is no future here A very good working environment with wide ranging amenities provided to the employees. Great fellow team members, who became a supportive family through the stressful and often downtrodden atmosphere'
 'Other than the working from home, holiday days amount and sick/ insurance perks, JP Morgan also strives to add back to the community. High turnover in store level management so if you want your own store you can get it pretty easily. _Everyone is world-class in everything they do, from PMs to Legal to Engineers who are some of the best around.'
 "Great Benefits, Lots of Travel Great place to start your career. Unlimited PTO is pointless if you can’t use the tile or it’s frowned upon which it is. But with great new hires they're working on making a difference."
 'Great company to work for, rapid growth potential!!! Listen to ideas if you have the receptive boss. Their goals are clear and they are consistent in applying policy while allowing reasonable room for variation. Long hours at times outside of busy season Lack of Job Security, Unstable Job Longevity'
 'Great company, strong exec leadership Service to country and camaraderie. lots of Hours, independant, challenging'
 'Great experience, not great growth propsects Strong focus on goals and working with a purpose. Development is still not transitioned. - Inefficient Processes make small things much bigger'
 "A fun and exciting place to work in the early days, now a bureaucratic, inefficent, and bloated company I'm not sure what to put here The company mis-leads its customers, they talk one thing and deliver something else, sweeping real issues under the carpet."
 'In terms of compensation, they give very similar to the industry standards but their bonus structure is pretty amazing. PE has the same comp as SWE, and Meta provides competitive benefits, like higher 401K employer match'
 'Management however is lacking severely. A rather good salary (In Russian terms) for specialists. They seem to be mostly home grown with little experience working in the industry.'
 'Great for future experiences. on the local level, management personnel management - Too much travel\r\n- Work life balance\r\n- Difficult to get on projects of your liking without previous background'
 'Excellent Starting Point and Career Experience Amat offers a veryCompetitive salary Great Work environment, colleagues and opportunities'
 'Best place to launch your career - Medical and 401k plans are not best\r\n- Most engagement will hit your work life balance hard. Bulk interviews so longe queues for your turn'
 "Generally positive especially if looking for new experience But don’t get it twisted! Operations wasn't for me, so I studied briefly and applied for an IT support role and got it! You can work a 8-5 shift Salary- The pay is ok but definitely under what others in the same positions at other companies are being paid starting out and they actually get 90 day reviews not to mention just feedback in general."
 'Move faster, layoffs, toxic psc a lot of overtime, tiring There is very little opportunity for advancement and promotions are given as a title with no pay increase.'
 "Company is passionate about keeping people safe and solving the world's most complex challenges. The employee creates his/her own objectives or is given a set of objectives that the manager expects from each team member at the beginning of each 6 month period."
 'Many real avenues to diversify technical learning opportunities, get broad exposure to leading edge technologies, feedback from massive customer base. No complaints no complaint no complaints'
 'Great office with great people in Old Town Scottsdale. Great to work for a company that is really trying to improve the world (reduce carbon footprint, thrust is on empowering every person and organization to do more, etc.) - WLB sometimes can be bad'
 'Great coworkers, managers, flexible schedule Cost of living in Cambridge, competition, long hours, poor work life balance in some groups Watch out for temporary positions they usually STAY temporary'
 'Increments appraisal system variable pay The discount sucks, and it’s very clique-y Review process allows for significant anonymous backstabbing & blame storming in times of declining defense bugets leading to a continuous number of ongoing RIFs.'
 'Great place to learn and work hard, but not to make money. -You get paid hourly and receive flexible hours Things start feeling repetitive after a while Don\'t compensate as well as they could and it makes using them as a "stepping stone" in switching to a more lucrative position with another company.'
 'My experience with American express has been the most professional & Employee friendly. Huge database available were you can expand your skill set. There is individual, corporate, hr, payroll and advisory area All that at the Corporate McDs.'
 'Passionate, smart people working in a great retail environment, backed by the best technology. Access to Tesco databases can provide stimulating work\r\nPositive departmental culture\r\nAcademically talented fellow employees\r\nGood work life balance\r\nGood opportunities Good culture depending what office you are based out of. Lots of learning opportunities in facebook'
 'Intense, rewarding culture Too many initiatives the company is investing but too few people - Yes, we eat too much! Some offices are way better at treating their employees than others, which will be evident by turnover rate.'
 'Good company, lots of perks Never ending overtime and very hectic! Not well organized\nDisappearing sense of community Very much fits into the culture of hospitality where employees are disposable.'
 "Worse place ever to work Multiple employees complained about the individual declining PTO request. A few researchers  are spoon-fed and groomed, given authorship on papers for doing very little, made PIs on grants they haven't written, pushed for exposure at conferences,  given cushy side projects and collaborations (e.g."
 'Over the last 5 to 6 years, Deloitte has lost its "soul". If you are not in the right project/client, no matter how super performing you are you cannot grow in the firm.'
 'and above all, nice cafetaria. On your feet all day.'
 'its a good experience. I worked with a lot of hardworking, dedicated, and kind people. large entity, lots of opportunity, inclusive and diverse work force, committed to a code of conduct respecting the individual, ethics and integrity and excellence in work product. Love working with pets, nice store, opportunity for advancement'
 'offers a wonderful product. I have not experienced any cons in this position. lack of sr management communication'
 'Manager, Technical Program Management The job was very straightforward, the system in use was easy to catch onto. Good hikes if you are a top performer'
 "Occasionally intense physical or dangerous work. No way Nothing bad to say You also don't get a break unless you work 7 hours and are over 21."
 'Great benefits and culture across most areas Low pay compared to industry standard The place runs like a schoolyard. Satya Nadella and his team are extremely visionary.'
 "An open, collaborative, innovative and flexible place to work. Flexible working hours and education system ability to learn new things here. I find that I'm learning from a LOT of my co-workers and I was a top 5%'er at my previous company of 300,000+ employees."
 'good salary could be better 2/ Very ethical and high on integrity.'
 "Be very sure of what you will be doing, don't just buy the brand! Sometimes received incorrect payment. Target schools get preferences."
 'Cut down the benefits and bring down the salaries rather than laying off people. People come in expecting a high level of service and high quality products. The pay is alright and there are significant benefits offered to part-timers who have been with the company for a year. welfare almost not exist. Work 10 HR days, no break no lunch no comp time micromanagement staffing issues denials of necessary time off-denial of funerals, expect Saturday and Sunday work weeks, no work from home,  but WFH is allowed if building is closed due to blizzards.'
 'Cutting Edge Research but the pace and drive to publish is fast Plethora of majors and minors; many resources for students and large alumni network Flexibility, generous compensation/total rewards, continuing education opportunities, constant mentorship and real time feedback. Diversity , continuous education , career opportunities,'
 "Love the technology and the peers! An FMCG SCHOOL and A PLACE TO LEARN They will still give you a bad review because they are unhappy with Booking.com and the company tries to blame you for it, doesn't matter how good you have been. Can be very metrics driven but with a good manager who understands that there are highs and lows with work production and external life, it seems very fair.."
 'Work Hard...Have Fun...Make history You can have the chance to work with senior leaders You are surrounded by talent most people transfer out of frustration waiting for a change. Only two or three were.'
 'great company to work Surrounded by smart people who became friends for life. Bunch of bullies would never go back.'
 'IBM can provide an excellent name to a resume with worldwide recognition and offer you insight into the world of IT that would be hard to find at most other IT employers. Competitive salary with provisions for personal growth and advancement. less increment and benefits\r\nless salary'
 "The people and technology at Morgan are superb. food and snacks in the office. Even if you don't make it to the brass ring, you build great skills and amazing network along the way that will pay big dividends later in life."
 '- Salary - Benefits - Historically: talented, friendly colleagues Nice and happy place to work A lot of moving parts.'
 'Excellent company to work for, except.... The 50% discount was great! Friendly work place\nGood benefits\nExcellent work life balance\nEmbracing industry standard of software development\nInvesting in training employees \nImproving infrastructure Nothing comes to mind .'
 'Highly Professional\r\nBrand Value\r\nValue Addition to CV - Dynamic\r\n- Good people.'
 'They need to clearly understand this and embrace it. CEO is arrogant and ignorant at the same time. Supervisors are a joke.'
 "Variety of job experience. Thomson Reuters, Focuses on innovation and developing products to support the ever growing needs, The company is know for his people friendliness and excellent work environment. As it's a huge organisation, bureaucracy can sometimes be a challenge."
 'No issues with upper mangement. Good work life balance offered Always Learn new things and meet new amazing people'
 'My team consisted of 9 males when we started, and over the course of three months, it grew to 15 males, and 0 females still. Progression is almost useless. Near public transit and a few coffee shops.'
 "Because of its size, the top employees are some of the brightest i've seen. unpredictable hours, scatterplot system is a joke Evening shift starts after midday."
 "Awful middle management GM's mold the policies to meet their own agenda. Managers are cool and all but again they abuse their power at times and never say sorry in front of other staffs, their egos are real as it can get Slow Growth opportunities, Cost saving mentality, Low adaptation strategy, No good insentives or reward very less bonus compared to other companies"
 'Software Engineer resident Best reason to work at CFA is, hands down, the people that you work with. Were always available. Free food,\nNice pay,\nGood culture'
 'great friends, tough life good environment, high salary, well team You can work in different technologies. Great diversity of people who work there'

In [19]:
cat_col=list(cat_col)
cat_col.remove('job_level')

df=df.drop(columns=cat_col,axis=1)

In [20]:
df.columns

Index(['job_level', 'tenure_months', 'salary', 'performance_score',
       'satisfaction_score', 'workload_score', 'team_sentiment',
       'project_completion_rate', 'overtime_hours', 'training_participation',
       'collaboration_score', 'email_sentiment', 'slack_activity',
       'meeting_participation', 'goal_achievement_rate', 'stress_level',
       'burnout_risk', 'left_company', 'turnover_probability_generated',
       'role_complexity_score', 'career_progression_score'],
      dtype='object')

In [21]:
len(list(num_col))

19

In [22]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

le=LabelEncoder()

df['job_level']=le.fit_transform(df['job_level'])
df['job_level']

0         3
1         2
2         0
3         2
4         3
         ..
849994    3
849995    0
849996    4
849997    3
849998    3
Name: job_level, Length: 849999, dtype: int64

In [23]:
corr = df.corr()
print(corr['burnout_risk'].sort_values(ascending=False))

burnout_risk                      1.000000
stress_level                      0.994221
turnover_probability_generated    0.592926
overtime_hours                    0.240957
left_company                      0.116192
training_participation            0.072186
role_complexity_score             0.004662
team_sentiment                    0.002773
salary                            0.000589
tenure_months                     0.000535
career_progression_score         -0.011056
job_level                        -0.013228
performance_score                -0.106267
goal_achievement_rate            -0.106267
workload_score                   -0.403526
project_completion_rate          -0.423375
collaboration_score              -0.471630
meeting_participation            -0.471630
slack_activity                   -0.471630
satisfaction_score               -0.675306
email_sentiment                  -0.676294
Name: burnout_risk, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split
X=df.drop(columns=['burnout_risk',
                   'stress_level',
                   'turnover_probability_generated',
                   'left_company',
                   'team_sentiment',
                   'salary',
                   'tenure_months',
                   'goal_achievement_rate',
                   'meeting_participation',
                   'slack_activity',
                   'email_sentiment',
                   ],
          axis=1)

y=df['burnout_risk']

X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [25]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,root_mean_squared_error,r2_score

model = RandomForestRegressor(
    n_estimators=50,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    n_jobs=-1,
    random_state=42
)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

MAE=mean_absolute_error(y_test,y_pred)
RMSE=root_mean_squared_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)

In [26]:
print(MAE)
print(RMSE)
print(R2)

0.06506849908812132
0.10476659909498638
0.8905430380489322

In [27]:
print(X.columns)
X.corr()

Index(['job_level', 'performance_score', 'satisfaction_score',
       'workload_score', 'project_completion_rate', 'overtime_hours',
       'training_participation', 'collaboration_score',
       'role_complexity_score', 'career_progression_score'],
      dtype='object')

,job_level,performance_score,satisfaction_score,workload_score,project_completion_rate,overtime_hours,training_participation,collaboration_score,role_complexity_score,career_progression_score
job_level,1.000000,0.016139,-0.000956,-0.001794,0.018894,0.002896,0.001663,0.029935,0.020465,0.004559
performance_score,0.016139,1.000000,0.182166,-0.000701,0.945137,0.001322,0.127730,0.127049,-0.007926,0.352548
satisfaction_score,-0.000956,0.182166,1.000000,-0.001652,0.383768,0.002247,0.125376,0.699232,-0.000847,0.166580
workload_score,-0.001794,-0.000701,-0.001652,1.000000,0.134005,-0.616403,-0.001253,-0.001566,0.001068,-0.001267
project_completion_rate,0.018894,0.945137,0.383768,0.134005,1.000000,-0.077687,0.090892,0.267844,-0.008753,0.323005
overtime_hours,0.002896,0.001322,0.002247,-0.616403,-0.077687,1.000000,0.000331,0.000312,-0.000390,0.001894
training_participation,0.001663,0.127730,0.125376,-0.001253,0.090892,0.000331,1.000000,0.089227,0.001190,0.393578
collaboration_score,0.029935,0.127049,0.699232,-0.001566,0.267844,0.000312,0.089227,1.000000,0.003898,0.117168
role_complexity_score,0.020465,-0.007926,-0.000847,0.001068,-0.008753,-0.000390,0.001190,0.003898,1.000000,-0.000884
career_progression_score,0.004559,0.352548,0.166580,-0.001267,0.323005,0.001894,0.393578,0.117168,-0.000884,1.000000

In [28]:
import pickle

with open("burnout_model.pkl", "wb") as f:
    pickle.dump(model, f)

In [39]:
with open("std_scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

In [40]:
with open("std_scaler.pkl", "rb") as f:
    std_scaler = pickle.load(f)

In [29]:
features = [
    'job_level',
    'performance_score',
    'satisfaction_score',
    'workload_score',
    'project_completion_rate',
    'overtime_hours',
    'training_participation',
    'collaboration_score',
    'role_complexity_score',
    'career_progression_score'
]

with open("features.pkl", "wb") as f:
    pickle.dump(features, f)

In [30]:
def predict_burnout(input_data):
    import numpy as np

    input_array = np.array(input_data).reshape(1, -1)
    prediction = model.predict(input_array)

    return prediction[0]

In [31]:
def interpret_result(score):
    if score < 0.3:
        return "Low Burnout Risk"
    elif score < 0.7:
        return "Moderate Burnout Risk"
    else:
        return "High Burnout Risk"

In [32]:
import pandas as pd

importance = pd.Series(model.feature_importances_, index=features)
print(importance.sort_values(ascending=False))

satisfaction_score          5.676428e-01
workload_score              2.428738e-01
project_completion_rate     8.369742e-02
performance_score           5.636051e-02
training_participation      3.502478e-02
career_progression_score    1.428573e-02
job_level                   9.334580e-05
overtime_hours              1.315164e-05
collaboration_score         8.204141e-06
role_complexity_score       1.856806e-07
dtype: float64

In [33]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# LSTM needs 3D input: (samples, timesteps, features)
# We treat each row as a sequence of 1 timestep
lstm_scaler = MinMaxScaler()
X_train_lstm = lstm_scaler.fit_transform(X_train)
X_test_lstm  = lstm_scaler.transform(X_test)

# Reshape to (samples, 1, features)
X_train_lstm = X_train_lstm.reshape(X_train_lstm.shape[0], 1, X_train_lstm.shape[1])
X_test_lstm  = X_test_lstm.reshape(X_test_lstm.shape[0], 1, X_test_lstm.shape[1])

print("LSTM input shape:", X_train_lstm.shape)

LSTM input shape: (679999, 1, 10)

In [34]:
# Build and train LSTM model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

lstm_model = Sequential([
    LSTM(64, input_shape=(1, X_train_lstm.shape[2]), return_sequences=True),
    Dropout(0.2),
    LSTM(32, return_sequences=False),
    Dropout(0.2),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')   # output in [0,1] for burnout_risk
])

lstm_model.compile(optimizer='adam', loss='mse', metrics=['mae'])
lstm_model.summary()

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history = lstm_model.fit(
    X_train_lstm, y_train,
    epochs=50,
    batch_size=512,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=1
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 1, 64)          │        19,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1, 64)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 32,161 (125.63 KB)

 Trainable params: 32,161 (125.63 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 31s 18ms/step - loss: 0.0214 - mae: 0.0955 - val_loss: 7.0462e-04 - val_mae: 0.0218
Epoch 2/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 32s 10ms/step - loss: 0.0013 - mae: 0.0265 - val_loss: 2.8686e-04 - val_mae: 0.0119
Epoch 3/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 13s 11ms/step - loss: 8.3896e-04 - mae: 0.0201 - val_loss: 1.3021e-04 - val_mae: 0.0077
Epoch 4/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 20s 10ms/step - loss: 6.5974e-04 - mae: 0.0172 - val_loss: 1.3402e-04 - val_mae: 0.0086
Epoch 5/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 14s 11ms/step - loss: 5.3752e-04 - mae: 0.0152 - val_loss: 9.8779e-05 - val_mae: 0.0075
Epoch 6/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - loss: 4.3451e-04 - mae: 0.0135 - val_loss: 1.0794e-04 - val_mae: 0.0068
Epoch 7/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 3.6145e-04 - mae: 0.0122 - val_loss: 4.0953e-05 - val_mae: 0.0036
Epoch 8/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 3.1745e-04 - mae: 0.0112 - val_loss: 4.0338e-05 - val_mae: 0.0033
Epoch 9/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 2.8714e-04 - mae: 0.0106 - val_loss: 3.6813e-05 - val_mae: 0.0032
Epoch 10/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 2.6368e-04 - mae: 0.0100 - val_loss: 4.9655e-05 - val_mae: 0.0037
Epoch 11/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 2.4335e-04 - mae: 0.0096 - val_loss: 2.6024e-05 - val_mae: 0.0028
Epoch 12/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 2.2741e-04 - mae: 0.0092 - val_loss: 2.9902e-05 - val_mae: 0.0035
Epoch 13/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 13s 11ms/step - loss: 2.1702e-04 - mae: 0.0089 - val_loss: 1.9538e-05 - val_mae: 0.0027
Epoch 14/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - loss: 2.0496e-04 - mae: 0.0086 - val_loss: 2.1714e-05 - val_mae: 0.0030
Epoch 15/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 2.0206e-04 - mae: 0.0086 - val_loss: 4.9350e-05 - val_mae: 0.0041
Epoch 16/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 13s 11ms/step - loss: 1.9135e-04 - mae: 0.0083 - val_loss: 5.1834e-05 - val_mae: 0.0050
Epoch 17/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 1.8589e-04 - mae: 0.0082 - val_loss: 2.4221e-05 - val_mae: 0.0031
Epoch 18/50
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 1.8144e-04 - mae: 0.0081 - val_loss: 2.6410e-05 - val_mae: 0.0028

In [35]:
# Evaluate LSTM
from sklearn.metrics import mean_absolute_error, r2_score

y_pred_lstm = lstm_model.predict(X_test_lstm).flatten()

print("LSTM MAE:", mean_absolute_error(y_test, y_pred_lstm))
print("LSTM R2 :", r2_score(y_test, y_pred_lstm))

# Compare with Random Forest
print("\nRF  MAE:", MAE)
print("RF  R2 :", R2)

5313/5313 ━━━━━━━━━━━━━━━━━━━━ 12s 2ms/step
LSTM MAE: 0.0027522079141958974
LSTM R2 : 0.9998029949282171

RF  MAE: 0.06506849908812132
RF  R2 : 0.8905430380489322

In [36]:
#Save LSTM model and scaler
import pickle

lstm_model.save("burnout_lstm_model.keras")

with open("lstm_scaler.pkl", "wb") as f:
    pickle.dump(lstm_scaler, f)

print("LSTM model and scaler saved!")

LSTM model and scaler saved!

In [52]:
# Ensemble prediction (RF + LSTM combined)
def predict_burnout_ensemble(input_data):
    """Combines RF and LSTM predictions with equal weight."""
    import numpy as np

    arr = np.array(input_data).reshape(1, -1)

    # RF prediction (uses StandardScaler from training)
    rf_pred = model.predict(arr)[0]

    # LSTM prediction (uses MinMaxScaler)
    arr_scaled = lstm_scaler.transform(arr).reshape(1, 1, -1)
    lstm_pred  = lstm_model.predict(arr_scaled, verbose=0)[0][0]

    ensemble = (0.2 * rf_pred) + (0.8 * lstm_pred)
    return round(float(ensemble), 4)

# Quick test
sample = X_test[0]          # already StandardScaler-scaled for RF
raw_sample = scaler.inverse_transform(sample.reshape(1, -1))[0]  # get raw values
print("Ensemble prediction:", predict_burnout_ensemble(raw_sample))
print("Interpretation:", interpret_result(predict_burnout_ensemble(raw_sample)))

Ensemble prediction: 0.7223
Interpretation: High Burnout Risk

In [51]:
# Compare Train vs Test for both models
from sklearn.metrics import r2_score, mean_absolute_error

# LSTM
y_train_pred_lstm = lstm_model.predict(X_train_lstm).flatten()
y_test_pred_lstm  = lstm_model.predict(X_test_lstm).flatten()

# RF
y_train_pred_rf = model.predict(X_train)

print("========== LSTM ==========")
print(f"Train R2  : {r2_score(y_train, y_train_pred_lstm):.6f}")
print(f"Test  R2  : {r2_score(y_test,  y_test_pred_lstm):.6f}")
print(f"Train MAE : {mean_absolute_error(y_train, y_train_pred_lstm):.6f}")
print(f"Test  MAE : {mean_absolute_error(y_test,  y_test_pred_lstm):.6f}")

print("\n========== Random Forest ==========")
print(f"Train R2  : {r2_score(y_train, y_train_pred_rf):.6f}")
print(f"Test  R2  : {r2_score(y_test,  y_pred):.6f}")
print(f"Train MAE : {mean_absolute_error(y_train, y_train_pred_rf):.6f}")
print(f"Test  MAE : {mean_absolute_error(y_test,  y_pred):.6f}")

21250/21250 ━━━━━━━━━━━━━━━━━━━━ 48s 2ms/step
5313/5313 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step
========== LSTM ==========
Train R2  : 0.999802
Test  R2  : 0.999803
Train MAE : 0.002750
Test  MAE : 0.002752

========== Random Forest ==========
Train R2  : 0.893009
Test  R2  : 0.890543
Train MAE : 0.064023
Test  MAE : 0.065068

In [53]:
# See individual model predictions
arr = np.array(raw_sample).reshape(1, -1)

rf_pred   = model.predict(scaler.transform(arr))[0]
arr_lstm  = lstm_scaler.transform(arr).reshape(1, 1, -1)
lstm_pred = lstm_model.predict(arr_lstm, verbose=0)[0][0]

print(f"RF   prediction : {rf_pred:.4f}")
print(f"LSTM prediction : {lstm_pred:.4f}")
print(f"Weighted ensemble (20% RF + 80% LSTM): {(0.2 * rf_pred) + (0.8 * lstm_pred):.4f}")

RF   prediction : 0.9145
LSTM prediction : 0.7411
Weighted ensemble (20% RF + 80% LSTM): 0.7757

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [54]:
# IMPORTANT
# Simulate weekly progression for an employee
def simulate_burnout_progression(base_input, weeks=8):
    """
    Gradually worsens key stress indicators week by week
    to simulate burnout building over time.
    """
    results = []
    inp = base_input.copy()

    for week in range(1, weeks + 1):
        score = predict_burnout_ensemble(inp)
        results.append({
            'week': f'Week {week}',
            'score': score,
            'risk': interpret_result(score)
        })

        # Gradually worsen conditions each week
        inp[4] -= 0.03   # project_completion_rate drops
        inp[5] += 1.5    # overtime_hours increases
        inp[2] -= 0.2    # satisfaction_score drops
        inp[3] += 0.3    # workload_score increases
        inp[6] -= 0.02   # training_participation drops

        # Clip to valid ranges
        inp[4] = max(0.0, inp[4])
        inp[5] = min(40,  inp[5])
        inp[2] = max(0.0, inp[2])
        inp[3] = min(10,  inp[3])
        inp[6] = max(0.0, inp[6])

    return pd.DataFrame(results)

# Test it
base = raw_sample.tolist()
progression_df = simulate_burnout_progression(base)
print(progression_df)

     week   score               risk
0  Week 1  0.7223  High Burnout Risk
1  Week 2  0.7416  High Burnout Risk
2  Week 3  0.7418  High Burnout Risk
3  Week 4  0.7665  High Burnout Risk
4  Week 5  0.7938  High Burnout Risk
5  Week 6  0.8205  High Burnout Risk
6  Week 7  0.8468  High Burnout Risk
7  Week 8  0.8883  High Burnout Risk

In [4]:
pip install streamlit

Collecting streamlit
  Downloading streamlit-1.55.0-py3-none-any.whl.metadata (9.8 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.0.5-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (8.3.1)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: packaging>=20 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Collecting protobuf<7,>=3.20 (from streamlit)
  Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: pyarrow>=7.0 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (23.0.1)
Requirement already satisfied: requests<3,>=2.27 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (2.32.4)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (6.5.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (4.14.1)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Requirement already satisfied: jinja2 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.0)
Collecting narwhals>=1.27.1 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading narwhals-2.18.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: colorama in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.27.0)
Requirement already satisfied: six>=1.5 in c:\users\rucha\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.55.0-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   --------- ------------------------------ 2.1/9.1 MB 10.8 MB/s eta 0:00:01
   ------------------- -------------------- 4.5/9.1 MB 10.9 MB/s eta 0:00:01
   ------------------------------ --------- 6.8/9.1 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------  8.9/9.1 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 10.2 MB/s  0:00:00
Downloading altair-6.0.0-py3-none-any.whl (795 kB)
   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--
   ---------------------------------------- 795.4/795.4 kB 5.1 MB/s  0:00:00
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-7.0.5-py3-none-any.whl (13 kB)
Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl (437 kB)
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--
   ------------- -------------------------- 2.4/6.9 MB 12.0 MB/s eta 0:00:01
   --------------------------- ------------ 4.7/6.9 MB 11.9 MB/s eta 0:00:01
   ---------------------------------------  6.8/6.9 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 6.9/6.9 MB 10.4 MB/s  0:00:00
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading narwhals-2.18.1-py3-none-any.whl (444 kB)
Installing collected packages: watchdog, toml, tenacity, smmap, protobuf, narwhals, cachetools, blinker, pydeck, gitdb, gitpython, altair, streamlit

   ----------------------------------------  0/13 [watchdog]
   ------ ---------------------------------  2/13 [tenacity]
   --------- ------------------------------  3/13 [smmap]
   ------------ ---------------------------  4/13 [protobuf]
   ------------ ---------------------------  4/13 [protobuf]
   ------------ ---------------------------  4/13 [protobuf]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   --------------- ------------------------  5/13 [narwhals]
   ------------------ ---------------------  6/13 [cachetools]
   ------------------------ ---------------  8/13 [pydeck]
   ------------------------ ---------------  8/13 [pydeck]
   ------------------------ ---------------  8/13 [pydeck]
   --------------------------- ------------  9/13 [gitdb]
   ------------------------------ --------- 10/13 [gitpython]
   ------------------------------ --------- 10/13 [gitpython]
   ------------------------------ --------- 10/13 [gitpython]
   --------------------------------- ------ 11/13 [altair]
   --------------------------------- ------ 11/13 [altair]
   --------------------------------- ------ 11/13 [altair]
   --------------------------------- ------ 11/13 [altair]
   --------------------------------- ------ 11/13 [altair]
   --------------------------------- ------ 11/13 [altair]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ------------------------------------ --- 12/13 [streamlit]
   ---------------------------------------- 13/13 [streamlit]

Successfully installed altair-6.0.0 blinker-1.9.0 cachetools-7.0.5 gitdb-4.0.12 gitpython-3.1.46 narwhals-2.18.1 protobuf-6.33.6 pydeck-0.9.1 smmap-5.0.3 streamlit-1.55.0 tenacity-9.1.4 toml-0.10.2 watchdog-6.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import streamlit as st
import pickle
import numpy as np

model = pickle.load(open("burnout_model.pkl", "rb"))

st.title("Burnout Prediction System")

work_hours = st.number_input("Work Hours")
fatigue = st.number_input("Mental Fatigue")

if st.button("Predict"):
    result = model.predict([[work_hours, fatigue]])
    st.write("Prediction:", result[0])

FileNotFoundError: [Errno 2] No such file or directory: 'burnout_model.pkl'

In [6]:
import pickle

# Save model
pickle.dump(model, open("burnout_model.pkl", "wb"))

# Save columns (VERY IMPORTANT)
pickle.dump(X.columns.tolist(), open("columns.pkl", "wb"))

# Save encoder (if used)
pickle.dump(le, open("encoder.pkl", "wb"))

NameError: name 'model' is not defined

In [7]:
le = pickle.load(open("encoder.pkl", "rb"))

df['job_level'] = le.transform(df['job_level'])

FileNotFoundError: [Errno 2] No such file or directory: 'encoder.pkl'